---
micronaut:
  application:
    name: rental-agency

app:
  initialCars:
    - registration: AA-123-VV
      brand: Renault
      model: Capture
      category: SUV
    - registration: BB-456-UU
      brand: Ford
      model: Focus
      category: SUV

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''    
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update


---
datasources.default: {}